(function () {
    const now = Date.now();
    const day = 86400000;

    function pexels(id, w = 800) {
        return `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=${w}&fit=crop`;
    }

    window.HERO_IMAGE = pexels(1450360, 1920);

    const raw = [
        {
            id: "TC-AZKhf6e",
            slug: "Majestic-Elegance-Punta-Cana",
            name: "Majestic Elegance Punta Cana",
            destTag: "SUD",
            subDest: "Punta Cana",
            country: "République Dominicaine",
            location: "Bavaro Beach, Punta Cana - République Dominicaine",
            stars: 5,
            supplier: "Vacances Sunwing",
            carrier: "Sunwing Airlines",
            durationNights: 7,
            roomCategory: "Suite Junior Vue Mer",
            criteria: ["Vue mer", "Familial", "Casino"],
            inventory: 3,
            price: 1459,
            packageType: "Forfait Tout-Inclus",
            endDateIn: 2,
            endDateExtra: 4500000,
            img: pexels(261102, 800),
            imgRoom: pexels(271624, 400),
            imgExtra: pexels(258154, 400),
            seoTags: ["#SUD", "#PUNTA_CANA", "#REPUBLIQUE_DOMINICAINE", "#TOUT_INCLUS", "#VOYAGE_FAMILLE"]
        },
        {
            id: "TC-BXLhf7f",
            slug: "Riu-Palace-Peninsula",
            name: "Riu Palace Peninsula",
            destTag: "SUD",
            subDest: "Cancun",
            country: "Mexique",
            location: "Cancun Hotel Zone, Cancun - Mexique",
            stars: 5,
            supplier: "Vacances Air Canada",
            carrier: "Air Canada Rouge",
            durationNights: 7,
            roomCategory: "Suite Standard",
            criteria: ["Familial", "Glissades d'eau"],
            inventory: 0,
            price: 1689,
            packageType: "Forfait Tout-Inclus",
            endDateIn: 1,
            endDateExtra: 3600000,
            img: pexels(2491287, 800),
            imgRoom: pexels(271743, 400),
            imgExtra: pexels(258154, 400),
            seoTags: ["#SUD", "#CANCUN", "#MEXIQUE", "#TOUT_INCLUS", "#VOYAGE_FAMILLE"]
        },
        {
            id: "TC-CYMhg8g",
            slug: "Margaritaville-Island-Reserve",
            name: "Margaritaville Island Reserve",
            destTag: "SUD",
            subDest: "Riviera Maya",
            country: "Mexique",
            location: "Riviera Maya, Mexique",
            stars: 4,
            supplier: "Vacances Transat",
            carrier: "Air Transat",
            durationNights: 14,
            roomCategory: "Suite Swim Out",
            criteria: ["Swim Out", "Adultes seulement", "Ambiance"],
            inventory: 2,
            price: 2890,
            packageType: "Forfait Tout-Inclus",
            endDateIn: 5,
            img: pexels(1450360, 800),
            imgRoom: pexels(189296, 400),
            imgExtra: pexels(1134176, 400),
            seoTags: ["#SUD", "#RIVIERA_MAYA", "#MEXIQUE", "#TOUT_INCLUS", "#ADULTES_SEULEMENT"]
        },
        {
            id: "TC-DZNih9h",
            slug: "Hotel-Riu-Plaza-Espana",
            name: "Hotel Riu Plaza España",
            destTag: "EUROPE",
            subDest: "Madrid",
            country: "Espagne",
            location: "Gran Vía, Madrid - Espagne",
            stars: 4,
            supplier: "Vacances Air Canada",
            carrier: "Air Canada",
            durationNights: 7,
            roomCategory: "Chambre Standard",
            criteria: ["En ville"],
            inventory: 5,
            price: 1850,
            packageType: "Forfait Plan Européen",
            endDateIn: 3,
            img: pexels(612366, 800),
            imgRoom: pexels(271624, 400),
            imgExtra: pexels(1029604, 400),
            seoTags: ["#EUROPE", "#MADRID", "#ESPAGNE", "#PLAN_EUROPEEN", "#EN_VILLE"]
        },
        {
            id: "TC-EABjk1a",
            slug: "Royal-Caribbean-Oasis",
            name: "Royal Caribbean Oasis of the Seas",
            destTag: "CROISIÈRE",
            subDest: "Miami",
            country: "Caraïbes",
            location: "Départ de Miami - Caraïbes occidentales",
            stars: 4,
            supplier: "Vacances Transat",
            carrier: "Air Transat",
            durationNights: 7,
            roomCategory: "Cabine Balcon",
            criteria: ["Adultes seulement", "Vue mer"],
            inventory: 4,
            price: 2199,
            packageType: "Forfait Croisière",
            endDateIn: 4,
            img: pexels(1619569, 800),
            imgRoom: pexels(271743, 400),
            imgExtra: pexels(1450360, 400),
            seoTags: ["#CROISIERE", "#MIAMI", "#CARAIBES", "#ADULTES_SEULEMENT"]
        },
        {
            id: "TC-FBCkl2b",
            slug: "Circuit-Rome-Florence",
            name: "Circuit Rome & Florence",
            destTag: "CIRCUIT",
            subDest: "Rome",
            country: "Italie",
            location: "Rome & Florence - Italie",
            stars: 4,
            supplier: "Vacances Air Canada",
            carrier: "Air Canada",
            durationNights: 14,
            roomCategory: "Hôtel 4 étoiles",
            criteria: ["En ville"],
            inventory: 6,
            price: 3290,
            packageType: "Forfait Circuit",
            endDateIn: 6,
            img: pexels(1797160, 800),
            imgRoom: pexels(1174732, 400),
            imgExtra: pexels(338515, 400),
            seoTags: ["#CIRCUIT", "#ROME", "#FLORENCE", "#ITALIE", "#EN_VILLE"]
        },
        {
            id: "TC-GCDlm3c",
            slug: "Fairmont-Chateau-Frontenac",
            name: "Fairmont Le Château Frontenac",
            destTag: "CANADA",
            subDest: "Québec",
            country: "Canada",
            location: "Vieux-Québec, Québec - Canada",
            stars: 5,
            supplier: "Vacances WestJet Québec",
            carrier: "WestJet",
            durationNights: 7,
            roomCategory: "Chambre Deluxe",
            criteria: ["En ville", "Golf"],
            inventory: 8,
            price: 1250,
            packageType: "Forfait Plan Européen",
            endDateIn: 3,
            img: pexels(1543841, 800),
            imgRoom: pexels(271624, 400),
            imgExtra: pexels(325061, 400),
            seoTags: ["#CANADA", "#QUEBEC", "#EN_VILLE", "#GOLF"]
        },
        {
            id: "TC-HDEmn4d",
            slug: "The-Venetian-Las-Vegas",
            name: "The Venetian Las Vegas",
            destTag: "USA",
            subDest: "Las Vegas",
            country: "États-Unis",
            location: "The Strip, Las Vegas - Nevada",
            stars: 5,
            supplier: "Vacances Sunwing",
            carrier: "Sunwing Airlines",
            durationNights: 7,
            roomCategory: "Suite Luxe",
            criteria: ["Adultes seulement", "Casino"],
            inventory: 1,
            price: 1599,
            packageType: "Forfait Vol + Hôtel",
            endDateIn: 2,
            img: pexels(1764208, 800),
            imgRoom: pexels(189296, 400),
            imgExtra: pexels(1268855, 400),
            seoTags: ["#USA", "#LAS_VEGAS", "#ADULTES_SEULEMENT", "#CASINO"]
        },
        {
            id: "TC-IEFno5e",
            slug: "Sandals-Grande-St-Lucian",
            name: "Sandals Grande St Lucian",
            destTag: "SUD",
            subDest: "Sainte-Lucie",
            country: "Sainte-Lucie",
            location: "Rodney Bay, Sainte-Lucie",
            stars: 5,
            supplier: "Vacances Transat",
            carrier: "Air Transat",
            durationNights: 7,
            roomCategory: "Suite Swim Out",
            criteria: ["Swim Out", "Adultes seulement", "Vue mer"],
            inventory: 2,
            price: 2499,
            packageType: "Forfait Tout-Inclus",
            endDateIn: 5,
            img: pexels(457881, 800),
            imgRoom: pexels(271743, 400),
            imgExtra: pexels(1450351, 400),
            seoTags: ["#SUD", "#SAINTE_LUCIE", "#SWIM_OUT", "#ADULTES_SEULEMENT"]
        },
        {
            id: "TC-JFGop6f",
            slug: "Bahia-Principe-Tulum",
            name: "Bahia Principe Tulum",
            destTag: "SUD",
            subDest: "Riviera Maya",
            country: "Mexique",
            location: "Akumal, Riviera Maya - Mexique",
            stars: 3,
            supplier: "Vacances WestJet Québec",
            carrier: "WestJet",
            durationNights: 7,
            roomCategory: "Chambre Standard",
            criteria: ["Familial", "Glissades d'eau"],
            inventory: 7,
            price: 999,
            packageType: "Forfait Tout-Inclus",
            endDateIn: 3,
            img: pexels(1450363, 800),
            imgRoom: pexels(271624, 400),
            imgExtra: pexels(1268848, 400),
            seoTags: ["#SUD", "#RIVIERA_MAYA", "#MEXIQUE", "#FAMILIAL", "#GLISSADES"]
        },
        {
            id: "TC-KGHpq7g",
            slug: "Barcelo-Bavaro-Palace",
            name: "Barceló Bávaro Palace",
            destTag: "SUD",
            subDest: "Punta Cana",
            country: "République Dominicaine",
            location: "Bávaro, Punta Cana - République Dominicaine",
            stars: 4,
            supplier: "Vacances Sunwing",
            carrier: "Sunwing Airlines",
            durationNights: 14,
            roomCategory: "Suite Junior",
            criteria: ["Golf", "Familial", "Vue mer"],
            inventory: 3,
            price: 1999,
            packageType: "Forfait Tout-Inclus",
            endDateIn: 7,
            img: pexels(261102, 800),
            imgRoom: pexels(271743, 400),
            imgExtra: pexels(325061, 400),
            seoTags: ["#SUD", "#PUNTA_CANA", "#GOLF", "#FAMILIAL", "#VUE_MER"]
        },
        {
            id: "TC-LHIqr8h",
            slug: "Hotel-Metropole-Monaco",
            name: "Hôtel Le Métropole Monaco",
            destTag: "EUROPE",
            subDest: "Monaco",
            country: "Monaco",
            location: "Monte-Carlo, Monaco",
            stars: 5,
            supplier: "Vacances Transat",
            carrier: "Air Transat",
            durationNights: 7,
            roomCategory: "Chambre Vue Mer",
            criteria: ["Vue mer", "Adultes seulement"],
            inventory: 4,
            price: 3290,
            packageType: "Forfait Plan Européen",
            endDateIn: 4,
            img: pexels(338515, 800),
            imgRoom: pexels(189296, 400),
            imgExtra: pexels(338504, 400),
            seoTags: ["#EUROPE", "#MONACO", "#VUE_MER", "#ADULTES_SEULEMENT"]
        },
        {
            id: "TC-MIJrs9i",
            slug: "NH-Collection-Berlin",
            name: "NH Collection Berlin",
            destTag: "EUROPE",
            subDest: "Berlin",
            country: "Allemagne",
            location: "Friedrichstrasse, Berlin - Allemagne",
            stars: 3,
            supplier: "Vacances WestJet Québec",
            carrier: "WestJet",
            durationNights: 7,
            roomCategory: "Chambre Standard",
            criteria: ["En ville"],
            inventory: 6,
            price: 1299,
            packageType: "Forfait Plan Européen",
            endDateIn: 2,
            img: pexels(209786, 800),
            imgRoom: pexels(271624, 400),
            imgExtra: pexels(1029604, 400),
            seoTags: ["#EUROPE", "#BERLIN", "#ALLEMAGNE", "#EN_VILLE"]
        },
        {
            id: "TC-NJKst0j",
            slug: "MSC-Meraviglia",
            name: "MSC Meraviglia",
            destTag: "CROISIÈRE",
            subDest: "Barcelone",
            country: "Méditerranée",
            location: "Départ de Barcelone - Méditerranée occidentale",
            stars: 4,
            supplier: "Vacances Air Canada",
            carrier: "Air Canada",
            durationNights: 14,
            roomCategory: "Cabine Extérieure",
            criteria: ["Familial", "Vue mer"],
            inventory: 5,
            price: 2799,
            packageType: "Forfait Croisière",
            endDateIn: 8,
            img: pexels(1263287, 800),
            imgRoom: pexels(271743, 400),
            imgExtra: pexels(1285625, 400),
            seoTags: ["#CROISIERE", "#BARCELONE", "#MEDITERRANEE", "#FAMILIAL"]
        }
    ];

    const destLabels = {
        SUD: "Sud",
        EUROPE: "Europe",
        "CROISIÈRE": "Croisière",
        CIRCUIT: "Circuit",
        CANADA: "Canada",
        USA: "États-Unis"
    };

    window.products = raw.map(p => ({
        ...p,
        destLabel: destLabels[p.destTag] || p.destTag,
        endDate: new Date(now + (p.endDateIn || 3) * day + (p.endDateExtra || 0))
    }));

    window.getProductBySlug = function (slug) {
        return window.products.find(p => p.slug === slug);
    };
})();
