(function () {
    const now = Date.now();
    const day = 86400000;

    const raw = [
        {
            id: "TC-AZKhf6e",
            slug: "Majestic-Elegance-Punta-Cana",
            name: "Majestic Elegance Punta Cana",
            destTag: "SUD",
            subDest: "Punta Cana",
            country: "République Dominicaine",
            location: "Bavaro Beach, Punta Cana - République Dominicaine",
            stars: 5,
            supplier: "Vacances Sunwing",
            carrier: "Sunwing Airlines",
            durationNights: 7,
            roomCategory: "Suite Junior Vue Mer",
            criteria: ["Vue mer", "Familial", "Casino"],
            inventory: 3,
            price: 1459,
            packageType: "Forfait Tout-Inclus",
            endDateIn: 2,
            endDateExtra: 4500000,
            img: "https://images.unsplash.com/photo-1571008887538-b36bb970ef41?auto=format&fit=crop&w=800&q=80",
            imgRoom: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=400&q=80",
            imgExtra: "https://images.unsplash.com/photo-1582719478250-c89cae659dc6?auto=format&fit=crop&w=400&q=80",
            seoTags: ["#SUD", "#PUNTA_CANA", "#REPUBLIQUE_DOMINICAINE", "#TOUT_INCLUS", "#VOYAGE_FAMILLE"]
        },
        {
            id: "TC-BXLhf7f",
            slug: "Riu-Palace-Peninsula",
            name: "Riu Palace Peninsula",
            destTag: "SUD",
            subDest: "Cancun",
            country: "Mexique",
            location: "Cancun Hotel Zone, Cancun - Mexique",
            stars: 5,
            supplier: "Vacances Air Canada",
            carrier: "Air Canada Rouge",
            durationNights: 7,
            roomCategory: "Suite Standard",
            criteria: ["Familial", "Glissades d'eau"],
            inventory: 0,
            price: 1689,
            packageType: "Forfait Tout-Inclus",
            endDateIn: 1,
            endDateExtra: 3600000,
            img: "https://images.unsplash.com/photo-1520250497591-112f87240c4c?auto=format&fit=crop&w=800&q=80",
            imgRoom: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=400&q=80",
            imgExtra: "https://images.unsplash.com/photo-1575429198097-0415ec6d2c7a?auto=format&fit=crop&w=400&q=80",
            seoTags: ["#SUD", "#CANCUN", "#MEXIQUE", "#TOUT_INCLUS", "#VOYAGE_FAMILLE"]
        },
        {
            id: "TC-CYMhg8g",
            slug: "Margaritaville-Island-Reserve",
            name: "Margaritaville Island Reserve",
            destTag: "SUD",
            subDest: "Riviera Maya",
            country: "Mexique",
            location: "Riviera Maya, Mexique",
            stars: 4,
            supplier: "Vacances Transat",
            carrier: "Air Transat",
            durationNights: 14,
            roomCategory: "Suite Swim Out",
            criteria: ["Swim Out", "Adultes seulement", "Ambiance"],
            inventory: 2,
            price: 2890,
            packageType: "Forfait Tout-Inclus",
            endDateIn: 5,
            img: "https://images.unsplash.com/photo-1582719508461-905c593771df?auto=format&fit=crop&w=800&q=80",
            imgRoom: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=400&q=80",
            imgExtra: "https://images.unsplash.com/photo-1519046904214-96b7917d43fb?auto=format&fit=crop&w=400&q=80",
            seoTags: ["#SUD", "#RIVIERA_MAYA", "#MEXIQUE", "#TOUT_INCLUS", "#ADULTES_SEULEMENT"]
        },
        {
            id: "TC-DZNih9h",
            slug: "Hotel-Riu-Plaza-Espana",
            name: "Hotel Riu Plaza España",
            destTag: "EUROPE",
            subDest: "Madrid",
            country: "Espagne",
            location: "Gran Vía, Madrid - Espagne",
            stars: 4,
            supplier: "Vacances Air Canada",
            carrier: "Air Canada",
            durationNights: 7,
            roomCategory: "Chambre Standard",
            criteria: ["En ville"],
            inventory: 5,
            price: 1850,
            packageType: "Forfait Plan Européen",
            endDateIn: 3,
            img: "https://images.unsplash.com/photo-1539037116277-4db20889f2d3?auto=format&fit=crop&w=800&q=80",
            imgRoom: "https://images.unsplash.com/photo-1590490360182-c33abfc8bae0?auto=format&fit=crop&w=400&q=80",
            imgExtra: "https://images.unsplash.com/photo-1543783207-ec64e4b9532f?auto=format&fit=crop&w=400&q=80",
            seoTags: ["#EUROPE", "#MADRID", "#ESPAGNE", "#PLAN_EUROPEEN", "#EN_VILLE"]
        },
        {
            id: "TC-EABjk1a",
            slug: "Royal-Caribbean-Oasis",
            name: "Royal Caribbean Oasis of the Seas",
            destTag: "CROISIÈRE",
            subDest: "Miami",
            country: "Caraïbes",
            location: "Départ de Miami - Caraïbes occidentales",
            stars: 4,
            supplier: "Vacances Transat",
            carrier: "Air Transat",
            durationNights: 7,
            roomCategory: "Cabine Balcon",
            criteria: ["Adultes seulement", "Vue mer"],
            inventory: 4,
            price: 2199,
            packageType: "Forfait Croisière",
            endDateIn: 4,
            img: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80",
            imgRoom: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=400&q=80",
            imgExtra: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=400&q=80",
            seoTags: ["#CROISIERE", "#MIAMI", "#CARAIBES", "#ADULTES_SEULEMENT"]
        },
        {
            id: "TC-FBCkl2b",
            slug: "Circuit-Rome-Florence",
            name: "Circuit Rome & Florence",
            destTag: "CIRCUIT",
            subDest: "Rome",
            country: "Italie",
            location: "Rome & Florence - Italie",
            stars: 4,
            supplier: "Vacances Air Canada",
            carrier: "Air Canada",
            durationNights: 14,
            roomCategory: "Hôtel 4 étoiles",
            criteria: ["En ville"],
            inventory: 6,
            price: 3290,
            packageType: "Forfait Circuit",
            endDateIn: 6,
            img: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80",
            imgRoom: "https://images.unsplash.com/photo-1523906834659-9d2308569ddb?auto=format&fit=crop&w=400&q=80",
            imgExtra: "https://images.unsplash.com/photo-1515542622106-78bda4ba0e5b?auto=format&fit=crop&w=400&q=80",
            seoTags: ["#CIRCUIT", "#ROME", "#FLORENCE", "#ITALIE", "#EN_VILLE"]
        },
        {
            id: "TC-GCDlm3c",
            slug: "Fairmont-Chateau-Frontenac",
            name: "Fairmont Le Château Frontenac",
            destTag: "CANADA",
            subDest: "Québec",
            country: "Canada",
            location: "Vieux-Québec, Québec - Canada",
            stars: 5,
            supplier: "Vacances WestJet Québec",
            carrier: "WestJet",
            durationNights: 7,
            roomCategory: "Chambre Deluxe",
            criteria: ["En ville", "Golf"],
            inventory: 8,
            price: 1250,
            packageType: "Forfait Plan Européen",
            endDateIn: 3,
            img: "https://images.unsplash.com/photo-1596462502279-4bf4c548ad33?auto=format&fit=crop&w=800&q=80",
            imgRoom: "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=400&q=80",
            imgExtra: "https://images.unsplash.com/photo-1535131749006-b7d5837d1d4c?auto=format&fit=crop&w=400&q=80",
            seoTags: ["#CANADA", "#QUEBEC", "#EN_VILLE", "#GOLF"]
        },
        {
            id: "TC-HDEmn4d",
            slug: "The-Venetian-Las-Vegas",
            name: "The Venetian Las Vegas",
            destTag: "USA",
            subDest: "Las Vegas",
            country: "États-Unis",
            location: "The Strip, Las Vegas - Nevada",
            stars: 5,
            supplier: "Vacances Sunwing",
            carrier: "Sunwing Airlines",
            durationNights: 7,
            roomCategory: "Suite Luxe",
            criteria: ["Adultes seulement", "Casino"],
            inventory: 1,
            price: 1599,
            packageType: "Forfait Vol + Hôtel",
            endDateIn: 2,
            img: "https://images.unsplash.com/photo-1605836567927-852558b87145?auto=format&fit=crop&w=800&q=80",
            imgRoom: "https://images.unsplash.com/photo-1595576507628-250690bed952?auto=format&fit=crop&w=400&q=80",
            imgExtra: "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=400&q=80",
            seoTags: ["#USA", "#LAS_VEGAS", "#ADULTES_SEULEMENT", "#CASINO"]
        },
        {
            id: "TC-IEFno5e",
            slug: "Sandals-Grande-St-Lucian",
            name: "Sandals Grande St Lucian",
            destTag: "SUD",
            subDest: "Sainte-Lucie",
            country: "Sainte-Lucie",
            location: "Rodney Bay, Sainte-Lucie",
            stars: 5,
            supplier: "Vacances Transat",
            carrier: "Air Transat",
            durationNights: 7,
            roomCategory: "Suite Swim Out",
            criteria: ["Swim Out", "Adultes seulement", "Vue mer"],
            inventory: 2,
            price: 2499,
            packageType: "Forfait Tout-Inclus",
            endDateIn: 5,
            img: "https://images.unsplash.com/photo-1580232173708-000d5f6439cb?auto=format&fit=crop&w=800&q=80",
            imgRoom: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=400&q=80",
            imgExtra: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=400&q=80",
            seoTags: ["#SUD", "#SAINTE_LUCIE", "#SWIM_OUT", "#ADULTES_SEULEMENT"]
        },
        {
            id: "TC-JFGop6f",
            slug: "Bahia-Principe-Tulum",
            name: "Bahia Principe Tulum",
            destTag: "SUD",
            subDest: "Riviera Maya",
            country: "Mexique",
            location: "Akumal, Riviera Maya - Mexique",
            stars: 3,
            supplier: "Vacances WestJet Québec",
            carrier: "WestJet",
            durationNights: 7,
            roomCategory: "Chambre Standard",
            criteria: ["Familial", "Glissades d'eau"],
            inventory: 7,
            price: 999,
            packageType: "Forfait Tout-Inclus",
            endDateIn: 3,
            img: "https://images.unsplash.com/photo-1520637838972-4ffeadcc60b3?auto=format&fit=crop&w=800&q=80",
            imgRoom: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=400&q=80",
            imgExtra: "https://images.unsplash.com/photo-1564507592339-c60657eea523?auto=format&fit=crop&w=400&q=80",
            seoTags: ["#SUD", "#RIVIERA_MAYA", "#MEXIQUE", "#FAMILIAL", "#GLISSADES"]
        },
        {
            id: "TC-KGHpq7g",
            slug: "Barcelo-Bavaro-Palace",
            name: "Barceló Bávaro Palace",
            destTag: "SUD",
            subDest: "Punta Cana",
            country: "République Dominicaine",
            location: "Bávaro, Punta Cana - République Dominicaine",
            stars: 4,
            supplier: "Vacances Sunwing",
            carrier: "Sunwing Airlines",
            durationNights: 14,
            roomCategory: "Suite Junior",
            criteria: ["Golf", "Familial", "Vue mer"],
            inventory: 3,
            price: 1999,
            packageType: "Forfait Tout-Inclus",
            endDateIn: 7,
            img: "https://images.unsplash.com/photo-1610641818980-b9f5d9585a24?auto=format&fit=crop&w=800&q=80",
            imgRoom: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=400&q=80",
            imgExtra: "https://images.unsplash.com/photo-1587174486073-9d1c513a1f8c?auto=format&fit=crop&w=400&q=80",
            seoTags: ["#SUD", "#PUNTA_CANA", "#GOLF", "#FAMILIAL", "#VUE_MER"]
        },
        {
            id: "TC-LHIqr8h",
            slug: "Hotel-Metropole-Monaco",
            name: "Hôtel Le Métropole Monaco",
            destTag: "EUROPE",
            subDest: "Monaco",
            country: "Monaco",
            location: "Monte-Carlo, Monaco",
            stars: 5,
            supplier: "Vacances Transat",
            carrier: "Air Transat",
            durationNights: 7,
            roomCategory: "Chambre Vue Mer",
            criteria: ["Vue mer", "Adultes seulement"],
            inventory: 4,
            price: 3290,
            packageType: "Forfait Plan Européen",
            endDateIn: 4,
            img: "https://images.unsplash.com/photo-1549144511-f099e773e34c?auto=format&fit=crop&w=800&q=80",
            imgRoom: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=400&q=80",
            imgExtra: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?auto=format&fit=crop&w=400&q=80",
            seoTags: ["#EUROPE", "#MONACO", "#VUE_MER", "#ADULTES_SEULEMENT"]
        },
        {
            id: "TC-MIJrs9i",
            slug: "NH-Collection-Berlin",
            name: "NH Collection Berlin",
            destTag: "EUROPE",
            subDest: "Berlin",
            country: "Allemagne",
            location: "Friedrichstrasse, Berlin - Allemagne",
            stars: 3,
            supplier: "Vacances WestJet Québec",
            carrier: "WestJet",
            durationNights: 7,
            roomCategory: "Chambre Standard",
            criteria: ["En ville"],
            inventory: 6,
            price: 1299,
            packageType: "Forfait Plan Européen",
            endDateIn: 2,
            img: "https://images.unsplash.com/photo-1560930950-5cc20e80e392?auto=format&fit=crop&w=800&q=80",
            imgRoom: "https://images.unsplash.com/photo-1598928506311-c55ded939a5c?auto=format&fit=crop&w=400&q=80",
            imgExtra: "https://images.unsplash.com/photo-1561283689-b62dbb40bc59?auto=format&fit=crop&w=400&q=80",
            seoTags: ["#EUROPE", "#BERLIN", "#ALLEMAGNE", "#EN_VILLE"]
        },
        {
            id: "TC-NJKst0j",
            slug: "MSC-Meraviglia",
            name: "MSC Meraviglia",
            destTag: "CROISIÈRE",
            subDest: "Barcelone",
            country: "Méditerranée",
            location: "Départ de Barcelone - Méditerranée occidentale",
            stars: 4,
            supplier: "Vacances Air Canada",
            carrier: "Air Canada",
            durationNights: 14,
            roomCategory: "Cabine Extérieure",
            criteria: ["Familial", "Vue mer"],
            inventory: 5,
            price: 2799,
            packageType: "Forfait Croisière",
            endDateIn: 8,
            img: "https://images.unsplash.com/photo-1599640843490-985aa4ac6ba5?auto=format&fit=crop&w=800&q=80",
            imgRoom: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=400&q=80",
            imgExtra: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=400&q=80",
            seoTags: ["#CROISIERE", "#BARCELONE", "#MEDITERRANEE", "#FAMILIAL"]
        }
    ];

    const destLabels = {
        SUD: "Sud",
        EUROPE: "Europe",
        "CROISIÈRE": "Croisière",
        CIRCUIT: "Circuit",
        CANADA: "Canada",
        USA: "États-Unis"
    };

    window.products = raw.map(p => ({
        ...p,
        destLabel: destLabels[p.destTag] || p.destTag,
        endDate: new Date(now + (p.endDateIn || 3) * day + (p.endDateExtra || 0))
    }));

    window.getProductBySlug = function (slug) {
        return window.products.find(p => p.slug === slug);
    };
})();
